// Character renderer: draws role agents from the Owner's sprite atlas
// (sprites/agents.png + sprites/agents.json, generated by scripts/build_agents_atlas.py)
// and falls back to the procedural sprites in sprites.ts for any missing frame.
import { ANCHOR_X, ANCHOR_Y, sprite, type Dir, type Pose } from "./sprites";

export type { Dir, Pose };
export type Variant = "female" | "male";
export type AgentStyle = "mixed" | "female" | "male";
export type IconName = "alert" | "talk" | "idea" | "done" | "question" | "sweat";

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
interface Manifest {
  cell: { w: number; h: number };
  anchor: { x: number; y: number };
  variants?: string[];
  roles?: string[];
  /** Optional uniform integer scale for every atlas frame (default ATLAS_SCALE). */
  scale?: number;
  frames: Record<string, Rect>;
  icons?: Record<string, Rect>;
  /** sholat[variant][pose]: one character per gender, same cell + anchor as frames */
  sholat?: Record<string, Record<string, Rect>>;
}

/** One uniform integer scale for all atlas frames (never per-frame). */
export const ATLAS_SCALE = 1;

// import.meta.glob compiles to {} when the files don't exist, so the build never breaks.
const pngUrls = import.meta.glob("./sprites/agents.png", { eager: true, query: "?url", import: "default" }) as Record<string, string>;
const jsons = import.meta.glob("./sprites/agents.json", { eager: true, import: "default" }) as Record<string, Manifest>;

const manifest: Manifest | null = Object.values(jsons)[0] ?? null;
let image: HTMLImageElement | null = null;
let ready = false;
const readyListeners = new Set<() => void>();
const counts = new Map<string, number>(); // "variant/role/pose/dir" -> frame count

if (manifest) {
  for (const key of Object.keys(manifest.frames)) {
    const i = key.lastIndexOf("/");
    const base = key.slice(0, i);
    counts.set(base, Math.max(counts.get(base) ?? 0, Number(key.slice(i + 1)) + 1));
  }
}
const url = Object.values(pngUrls)[0];
if (url && manifest) {
  image = new Image();
  image.onload = () => {
    ready = true;
    readyListeners.forEach((f) => f());
  };
  image.src = url;
}

export function atlasReady(): boolean {
  return ready;
}
export function onAtlasReady(fn: () => void): () => void {
  if (ready) fn();
  readyListeners.add(fn);
  return () => {
    readyListeners.delete(fn);
  };
}

// ------------------------------------------------------------------ agent style (variant choice)
const STYLE_KEY = "pc-agent-style";
let style: AgentStyle = (() => {
  try {
    const v = localStorage.getItem(STYLE_KEY);
    return v === "female" || v === "male" || v === "mixed" ? v : "mixed";
  } catch {
    return "mixed";
  }
})();
const styleListeners = new Set<() => void>();
export function getAgentStyle(): AgentStyle {
  return style;
}
export function setAgentStyle(s: AgentStyle) {
  style = s;
  try {
    localStorage.setItem(STYLE_KEY, s);
  } catch {
    /* storage unavailable */
  }
  styleListeners.forEach((f) => f());
}
export function subscribeAgentStyle(fn: () => void): () => void {
  styleListeners.add(fn);
  return () => {
    styleListeners.delete(fn);
  };
}

function strHash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}
/** Deterministic: Mixed = hash(projectId + role) % 2; HQ (no project) uses the role id alone. */
export function variantFor(project: string | null | undefined, role: string, s: AgentStyle = style): Variant {
  if (s !== "mixed") return s;
  if (role === "analyst") project = null;
  const vs = (manifest?.variants as Variant[] | undefined) ?? ["female", "male"];
  return vs[strHash((project ?? "") + role) % vs.length] ?? "male";
}

// ------------------------------------------------------------------ frame lookup
/** Office pose -> ordered atlas "pose/dir" candidates. */
function candidates(pose: Pose, dir: Dir): string[] {
  const any = (p: string) => [`${p}/${dir}`, `${p}/down`, `${p}/left`, `${p}/right`, `${p}/up`];
  switch (pose) {
    case "walk":
      return [...any("walk"), `idle/${dir}`, "idle/down"];
    case "sitType":
    case "sitIdle":
      // seated at a PC: the sheet's "work" frames face the viewer (monitor included);
      // backs-to-viewer seats use the up-facing idle frame cropped by the chair.
      return dir === "up" ? ["idle/up", "walk/up"] : ["work/down", "idle/down"];
    case "read":
      return ["tablet/down", `idle/${dir}`, "idle/down"];
    case "frustrated":
      return dir === "up" ? ["idle/up", "walk/up"] : ["work/down", "idle/down"];
    case "couch":
    case "stand":
    default:
      return [...any("idle"), "idle/down"];
  }
}

export type AtlasPose = "idle" | "walk" | "work" | "talk" | "tablet" | "portrait";

export interface Resolved {
  rect: Rect;
  pose: string;
  variant: Variant;
}

export function resolve(variant: Variant, role: string, pose: Pose, dir: Dir, frame: number, atlasPose?: AtlasPose): Resolved | null {
  if (!ready || !manifest) return null;
  const list = atlasPose ? [`${atlasPose}/${dir}`, `${atlasPose}/down`, ...candidates(pose, dir)] : candidates(pose, dir);
  const other: Variant = variant === "female" ? "male" : "female";
  for (const v of [variant, other])
    for (const c of list) {
      const n = counts.get(`${v}/${role}/${c}`);
      if (!n) continue;
      const rect = manifest.frames[`${v}/${role}/${c}/${frame % n}`] ?? manifest.frames[`${v}/${role}/${c}/0`];
      if (rect) return { rect, pose: c.split("/")[0], variant: v };
    }
  return null;
}

export function frameCount(variant: Variant, role: string, pose: Pose, dir: Dir): number {
  if (!ready) return pose === "walk" ? 4 : pose === "sitType" ? 3 : 2;
  for (const c of candidates(pose, dir)) {
    const n = counts.get(`${variant}/${role}/${c}`);
    if (n) return n;
  }
  return 1;
}

export interface Drawn extends Rect {
  atlas: boolean;
  pose: string;
}

/** Feet anchor offset of atlas frames (native px). */
function anchor() {
  const s = manifest?.scale ?? ATLAS_SCALE;
  return { x: (manifest?.anchor.x ?? 24) * s, y: (manifest?.anchor.y ?? 69) * s, s };
}

/**
 * Draw a character with its feet at (x, y) in native world px. Returns the bounding box of
 * the visible pixels (for hit-testing and bubble placement).
 */
export function drawCharacter(
  ctx: CanvasRenderingContext2D,
  variant: Variant,
  role: string,
  pose: Pose,
  dir: Dir,
  frame: number,
  x: number,
  y: number,
  atlasPose?: AtlasPose,
  pre?: Resolved | null,
): Drawn {
  const hit = pre === undefined ? resolve(variant, role, pose, dir, frame, atlasPose) : pre;
  if (hit && image) {
    const { x: ax, y: ay, s } = anchor();
    const r = hit.rect;
    const dx = Math.round(x - ax);
    const dy = Math.round(y - ay);
    ctx.drawImage(image, r.x, r.y, r.w, r.h, dx, dy, r.w * s, r.h * s);
    const bb = contentBox(r);
    return { x: dx + bb.x * s, y: dy + bb.y * s, w: bb.w * s, h: bb.h * s, atlas: true, pose: hit.pose };
  }
  const c = sprite(role, pose, dir, frame);
  const dx = Math.round(x - ANCHOR_X);
  const dy = Math.round(y - ANCHOR_Y);
  ctx.drawImage(c, dx, dy);
  return { x: dx + 2, y: dy + 2, w: 24, h: 40, atlas: false, pose };
}

// Opaque-pixel bounding box per atlas rect (computed once, lazily).
const bboxCache = new Map<string, Rect>();
let pixels: ImageData | null = null;
function contentBox(r: Rect): Rect {
  const key = `${r.x},${r.y}`;
  const hit = bboxCache.get(key);
  if (hit) return hit;
  if (!pixels && image) {
    const c = document.createElement("canvas");
    c.width = image.width;
    c.height = image.height;
    const g = c.getContext("2d")!;
    g.drawImage(image, 0, 0);
    try {
      pixels = g.getImageData(0, 0, c.width, c.height);
    } catch {
      pixels = null;
    }
  }
  let box: Rect = { x: 0, y: 0, w: r.w, h: r.h };
  if (pixels) {
    let x0 = r.w;
    let y0 = r.h;
    let x1 = -1;
    let y1 = -1;
    for (let y = 0; y < r.h; y++)
      for (let x = 0; x < r.w; x++)
        if (pixels.data[((r.y + y) * pixels.width + r.x + x) * 4 + 3] > 20) {
          if (x < x0) x0 = x;
          if (y < y0) y0 = y;
          if (x > x1) x1 = x;
          if (y > y1) y1 = y;
        }
    if (x1 >= 0) box = { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
  }
  bboxCache.set(key, box);
  return box;
}

/** Draw a sholat posture frame with its feet at (x, y). Returns the visible box, or null. */
export function drawSholat(ctx: CanvasRenderingContext2D, variant: Variant, pose: string, x: number, y: number, flipX = false): Rect | null {
  const set = manifest?.sholat?.[variant] ?? manifest?.sholat?.male;
  if (pose === "sit_back") return drawSitBack(ctx, set, x, y, flipX);
  const r = set?.[pose];
  if (!ready || !image || !r) return null;
  const { x: ax, y: ay, s } = anchor();
  const dx = Math.round(x - ax);
  const dy = Math.round(y - ay);
  if (flipX) {
    ctx.save();
    ctx.translate(dx + r.w * s, dy);
    ctx.scale(-1, 1);
    ctx.drawImage(image, r.x, r.y, r.w, r.h, 0, 0, r.w * s, r.h * s);
    ctx.restore();
  } else ctx.drawImage(image, r.x, r.y, r.w, r.h, dx, dy, r.w * s, r.h * s);
  const bb = contentBox(r);
  const bx = flipX ? r.w - bb.x - bb.w : bb.x;
  return { x: dx + bx * s, y: dy + bb.y * s, w: bb.w * s, h: bb.h * s };
}

/**
 * The atlas has no back-view sitting frame (duduk / tahiyat / salam from behind), so compose
 * one: the stand_back head + torso lowered onto its own feet, as if kneeling on the heels.
 */
function drawSitBack(ctx: CanvasRenderingContext2D, set: Record<string, Rect> | undefined, x: number, y: number, flipX: boolean): Rect | null {
  const st = set?.stand_back;
  if (!ready || !image || !st) return null;
  const { x: ax, y: ay, s } = anchor();
  const bb = contentBox(st);
  const torso = Math.round(bb.h * 0.64);
  const feet = 4;
  const drop = bb.h - torso - feet; // how far the torso sinks
  const dx = Math.round(x - ax);
  const dy = Math.round(y - ay);
  ctx.save();
  if (flipX) {
    ctx.translate(dx * 2 + st.w * s, 0);
    ctx.scale(-1, 1);
  }
  // feet first (behind), then the lowered torso over them
  ctx.drawImage(image, st.x, st.y + bb.y + bb.h - feet, st.w, feet, dx, dy + (bb.y + bb.h - feet) * s, st.w * s, feet * s);
  ctx.drawImage(image, st.x, st.y + bb.y, st.w, torso, dx, dy + (bb.y + drop) * s, st.w * s, torso * s);
  ctx.restore();
  return { x: dx + bb.x * s, y: dy + (bb.y + drop) * s, w: bb.w * s, h: (torso + feet) * s };
}

/** Draw an atlas status icon centred at (cx, bottom). Returns false when unavailable. */
export function drawIcon(ctx: CanvasRenderingContext2D, name: IconName, cx: number, bottom: number): boolean {
  const r = manifest?.icons?.[name];
  if (!ready || !image || !r) return false;
  ctx.drawImage(image, r.x, r.y, r.w, r.h, Math.round(cx - r.w / 2), Math.round(bottom - r.h), r.w, r.h);
  return true;
}

/** Portrait for cards/avatars: atlas portrait/down/0 for the variant, else the procedural bust. */
export function drawPortrait(ctx: CanvasRenderingContext2D, role: string, variant: Variant, w: number, h: number): void {
  ctx.clearRect(0, 0, w, h);
  const hit = ready && manifest ? (manifest.frames[`${variant}/${role}/portrait/down/0`] ?? manifest.frames[`${variant}/${role}/idle/down/0`]) : null;
  if (hit && image) {
    const bb = contentBox(hit);
    const fit = Math.min(w / bb.w, h / bb.h);
    // integer upscale when there is room, otherwise a plain downscale for tiny avatars
    const k = fit >= 1 ? Math.floor(fit) : fit;
    ctx.imageSmoothingEnabled = k < 1;
    const dw = Math.round(bb.w * k);
    const dh = Math.round(bb.h * k);
    ctx.drawImage(image, hit.x + bb.x, hit.y + bb.y, bb.w, bb.h, Math.round((w - dw) / 2), Math.round(h - dh), dw, dh);
    return;
  }
  const c = sprite(role, "stand", "down", 0);
  const sw = 24;
  const sh = 30;
  const k = Math.max(1, Math.floor(Math.min(w / sw, h / sh)));
  ctx.drawImage(c, 2, 0, sw, sh, Math.round((w - sw * k) / 2), Math.round(h - sh * k), sw * k, sh * k);
}
