// Loader for the Owner's office/mushola props atlas (sprites/props.png + props.json,
// generated by scripts/build_props_atlas.py). Props are already at the characters' scale.
import type { Ctx } from "./pixel";

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
interface PropManifest {
  props: Record<string, Rect & { kind: string }>;
  floors: Record<string, Rect>;
  rugs: Record<string, Rect>;
}

const pngs = import.meta.glob("./sprites/props.png", { eager: true, query: "?url", import: "default" }) as Record<string, string>;
const jsons = import.meta.glob("./sprites/props.json", { eager: true, import: "default" }) as Record<string, PropManifest>;
const manifest: PropManifest | null = Object.values(jsons)[0] ?? null;

let img: HTMLImageElement | null = null;
let ready = false;
const listeners = new Set<() => void>();
const url = Object.values(pngs)[0];
if (url && manifest) {
  img = new Image();
  img.onload = () => {
    ready = true;
    listeners.forEach((f) => f());
  };
  img.src = url;
}

export function propsReady() {
  return ready;
}
export function onPropsReady(fn: () => void): () => void {
  if (ready) fn();
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}

export function propSize(name: string): { w: number; h: number } | null {
  const r = manifest?.props[name] ?? manifest?.rugs[name];
  return r ? { w: r.w, h: r.h } : null;
}

export interface PropOpts {
  flipX?: boolean;
  flipY?: boolean;
  /** "bottom": (x,y) is the bottom-centre on the floor (default); "top": top-centre (wall decor); "tl": top-left */
  anchor?: "bottom" | "top" | "tl";
}

/** Draw a prop or rug. Returns its drawn rect, or null if unavailable. */
export function prop(ctx: Ctx, name: string, x: number, y: number, o: PropOpts = {}): Rect | null {
  const r = manifest?.props[name] ?? manifest?.rugs[name];
  if (!ready || !img || !r) return null;
  const a = o.anchor ?? "bottom";
  const dx = Math.round(a === "tl" ? x : x - r.w / 2);
  const dy = Math.round(a === "bottom" ? y - r.h : y);
  blit(ctx, r, dx, dy, r.w, r.h, o.flipX, o.flipY);
  return { x: dx, y: dy, w: r.w, h: r.h };
}

/** Draw a sub-rectangle of a prop (local coords) at a destination top-left. */
export function propPart(ctx: Ctx, name: string, sx: number, sy: number, sw: number, sh: number, dx: number, dy: number) {
  const r = manifest?.props[name];
  if (!ready || !img || !r) return;
  ctx.drawImage(img, r.x + sx, r.y + sy, sw, sh, Math.round(dx), Math.round(dy), sw, sh);
}

function blit(ctx: Ctx, r: Rect, dx: number, dy: number, w: number, h: number, fx?: boolean, fy?: boolean) {
  if (!fx && !fy) {
    ctx.drawImage(img!, r.x, r.y, r.w, r.h, dx, dy, w, h);
    return;
  }
  ctx.save();
  ctx.translate(dx + (fx ? w : 0), dy + (fy ? h : 0));
  ctx.scale(fx ? -1 : 1, fy ? -1 : 1);
  ctx.drawImage(img!, r.x, r.y, r.w, r.h, 0, 0, w, h);
  ctx.restore();
}

const patterns = new WeakMap<Ctx, Map<string, CanvasPattern>>();
/** Fill a rect with a seamless atlas floor texture. Returns false if unavailable. */
export function floorFill(ctx: Ctx, name: string, x: number, y: number, w: number, h: number): boolean {
  const r = manifest?.floors[name];
  if (!ready || !img || !r) return false;
  let m = patterns.get(ctx);
  if (!m) patterns.set(ctx, (m = new Map()));
  let p = m.get(name);
  if (!p) {
    const c = document.createElement("canvas");
    c.width = r.w;
    c.height = r.h;
    c.getContext("2d")!.drawImage(img, r.x, r.y, r.w, r.h, 0, 0, r.w, r.h);
    p = ctx.createPattern(c, "repeat")!;
    m.set(name, p);
  }
  ctx.save();
  ctx.fillStyle = p;
  // anchor the pattern to the world origin so adjacent fills line up
  ctx.fillRect(x, y, w, h);
  ctx.restore();
  return true;
}
